### ISSUE TITLE
Can't use npm installed modules.

### ISSUE THREAD

**Issue by airtonix** [axilleasiv/vscode-javascript-repl-docs#20]
vscode-remote > wsl2 alpine

start a project

```
$ npm init -f
$ npm install jsonpointer
$ code .
```

ctrl shift p > new repl 

```
var jsonpointer = require('jsonpointer');

```

error: can't find module jsonpointer

```
❯ npx envinfo
npx: installed 1 in 4.324s

  System:
    OS: Linux 4.4 Alpine Linux
    CPU: (8) x64 Intel(R) Core(TM) i7-7700HQ CPU @ 2.80GHz
    Memory: 6.19 GB / 31.86 GB
    Container: Yes
    Shell: 5.7.1 - /bin/zsh
  Binaries:
    Node: 13.8.0 - ~/.nvm/versions/node/v13.8.0/bin/node
    Yarn: 1.22.4 - ~/.nvm/versions/node/v13.8.0/bin/yarn
    npm: 6.13.6 - ~/.nvm/versions/node/v13.8.0/bin/npm
  Managers:
    pip3: 19.2.3 - /usr/bin/pip3
  Utilities:
    CMake: 3.15.5 - /usr/bin/cmake
    Make: 4.2.1 - /usr/bin/make
    GCC: 9.2.0 - /usr/bin/gcc
    Git: 2.24.3 - /usr/bin/git
  IDEs:
    VSCode: 1.48.0 - /home/zenobius/.vscode-server/bin/db40434f562994116e5b21c24015a2e40b2504e6/bin/code
  Languages:
    Bash: 5.0.11 - /bin/bash
    Python: 2.7.18 - /usr/bin/python
    Python3: 3.8.2 - /usr/bin/python3
```

```
[Window Title]
Visual Studio Code

[Main Instruction]
Visual Studio Code

[Content]

Version: 1.48.0 (system setup)
Commit: db40434f562994116e5b21c24015a2e40b2504e6
Date: 2020-08-13T07:50:42.600Z (5 days ago)
Electron: 7.3.2
Chrome: 78.0.3904.130
Node.js: 12.8.1
V8: 7.8.279.23-electron.0
OS: Windows_NT x64 10.0.20190

[OK] [Copy]
```

**Comment by airtonix** [comment]
you have to use es6 import... require doesn't work.

**Comment by axilleasiv** [comment]
Hey, @airtonix  thank you so much for your feedback!

The issue here is not the 'require' but a wrong decision that I made about how the "JS Repl: New Javascript File" it works. More specifically, when users are selecting the "New commands", these new files are temporary files outside of the current workspace folder, and the extension at the moment does not check the workspace folder for already installed node modules. 

I am planning to change this, and check automatically the workspace folder for installed modules. If there are more than one workspace folders in vscode, I am thinking to add a window prompt that will ask to select the main folder for this "New repl" command.

Until the next version, if you want to use the already installed modules in your workspace folder you can save a javascript file with your code and try the command ["JS Repl: Run"](https://github.com/axilleasiv/vscode-javascript-repl-docs/wiki/Commands#start-in-existed-file) on this file.

Additionally, if you want to require node modules by using the new commands like the "JS Repl: New Javascript File (.js)", you can do what you did and by hovering over the error and click "Install" module, the module will be installed in a temporary folder(after installation the error will be removed).

![image](https://user-images.githubusercontent.com/1872682/90696238-92856e80-e284-11ea-847e-aac6d98a2789.png)

Thanks again and let me know if you have any other issues.

**Comment by airtonix** [comment]
@axilleasiv  Thanks for that.

> I am planning to change this, and check automatically the workspace folder for installed modules. If there are more than one > workspace folders in vscode, I am thinking to add a window prompt that will ask to select the main folder for this "New repl" > command.

sounds reasonable, one suggestion:
- result of the modal question should set workspace settings `.vscode/setttings.json`
- modal question shouldn't appear if answer is already in `.vscode/setttings.json`
