### ISSUE TITLE
FR: made an option to create _empty_ files after running 'New ... file' commands

### ISSUE THREAD

**Issue by VKondakoff** [axilleasiv/vscode-javascript-repl-docs#7]
Currently running 'JS Repl: New ... file' commands creates new files, which contains usage examples. I think there should be an option in JS Repl settings to create an empty files after running 'Js Repl: New ... file' commands.

**Comment by axilleasiv** [comment]
@VKondakoff I like this idea. At the first release, my plan was the  'JS Repl: New ...' files to have only the following content
```
console.log('We \u2661 JavaScript!');
```
But before the release, I added the current content that you have already seen because I thought that it will be more helpful for first-time users.

Now, with your comment, I am thinking that for the users that have already been familiar with the actions and comments that are available through the extension, it is annoying and not necessary to delete every time the default content.

**Comment by axilleasiv** [comment]
@VKondakoff this config option has been added in the 0.6.2 version
